# -*- coding: utf-8 -*-

filter_list = [
    '(acoustic)',
    '(akustik)',
    'unplugged',
    'instrumental',
    'ampya',
    'seltensogelacht',
    'gameplay',
    '(full album stream)',
    #'(behind the video)',
    'behind the',
    #'(behind the scenes)',
    '(making.*?of)',
    'making.*?photoshoot',
    'making the video',
    'album photoshoot',
    'the documentary',
    'track commentary',
    'video commentary',
    'faceless documentary',
    'bts',
    'episode \d+',
    'webisode \d+',
    '\#\d+',
    'part \d+',
    'teil \d+',
    'beyond the video',
    'live @',
    'live at',
    'live in session',
    ' live from ',
    'live.*?\d+',
    'live.*?show',
    '\(live in .*?\)',
    '- live in ',
    'download festival',
    'living the dream foundation',
    #'tour diary',
    #'(from .+? tour)',
    'tour',
    'concert',
    'konzert',
    'studio update',
    'in the studio',
    'in studio series',
    'studio diary',
    'studio blog',
    'album teaser',
    'from the road',
    'on the road',
    'teaser',
    '\: the band',
    '\: the dream begins',
    'interview',
    'trailer',
    'the story of',
    'album release video',
    'an intimate performance',
    'performance \d+',
    'promo',
    'ep taster',
    'epk',
    'track\s*by\s*track',
    'sneak peek|peak',
    'log series',
    'intervista',
    'webclip',
    'bundle commercial',
    'creature fashion show',
    'auf deutsch',
    '(\[|\s*|\()sub \w+',
    'letra \w+',
    'untertitel',
    'minimix',
    'album release',
    'full.+?album',
    'full.+?ep',
    '\(song\)',
    'new song',
    '\[new\]',
    '\(audio\)',
    '\(.*?stream\)',
    'dsds',
    'new album',
    'in stores now',
    'pre(-||\s*)listening',
    'karaoke',
    'a cappella',
    'a capella',
    'live.*?unsigned',
    'dj(-|\s)mix',
    'dj(-|\s)set',
    'live(-|\s)set',
    '(\w+\s+\d{2+})',
    'ask:reply',
    'girl meets world',
    'stars dance',
    '(\d+ (day|days) to go)',
    '(signings)',
    'bring me to.*?:',
    'vault \d+',
    'videodays',
    'shoutout.*?festival',
    'one day (at|@).*?\d+',
    '\w+ records',
    '(parodie)',
    '(parody)',
    '\(.*?cover.*?\)',
    'inglés',
    'español',
    'tribute to',
    'guitar lesson',
    'un(-||\s)official',
    'officially official',
    '\(outtakes\)',
    '(drum||guitar)(-||\s*)play(-||\s*)through',
    '(album|official)(-||\s*)preview',
    'gmv',
    'q&a:',
    'music video official release',
    'subtitles',
    'announcement',
    ]